<a href="https://colab.research.google.com/github/Mountain-Biker/pydata-book-practice/blob/main/chapter5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5. Getting Started with pandas

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## 5.1 Introduction to pandas Data Structures

### Series

A Series is a one-dimensional array-like object containing a sequence of values of the same type and an associated array of data labels, called its index.

In [ ]:
obj = pd.Series([4, 5, -7, 3])

In [ ]:
obj

0    4
1    5
2   -7
3    3
dtype: int64

In [ ]:
obj2 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

In [ ]:
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
obj2['a']

np.int64(1)

In [ ]:
obj2['b'] = 6

In [ ]:
obj2[['a', 'b']] = -1

In [ ]:
obj2

a   -1
b   -1
c    3
d    4
dtype: int64

Using Numpy functions or Numpy-like operations, such as filtering with a Boolean array, scalar multiplication, or applying math functions, will preserve the index-value relationship.

In [ ]:
obj2[obj2 > 0]

c    3
d    4
dtype: int64

In [ ]:
obj2 * 2

a   -2
b   -2
c    6
d    8
dtype: int64

In [ ]:
np.exp(obj2)

a     0.367879
b     0.367879
c    20.085537
d    54.598150
dtype: float64

Another way to think about a Series is as a **fixed-length, ordered dictionary**, as it is a mapping of index values to data values. It can be used in many context where you might use a dictionary.

In [ ]:
'b' in obj2

True

In [ ]:
'e' in obj2

False

A series can be created from a dictionary.

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

A series can be converted back to a dictionary with its to_dict method.

In [ ]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [ ]:
states = ['California', 'Utah', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [ ]:
obj4

California        NaN
Utah           5000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

The isna and notna functions in pandas should be used to detect missing data.

In [ ]:
pd.isna(obj4)

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj4.isna()

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [ ]:
obj3 + obj4

California         NaN
Ohio               NaN
Oregon         32000.0
Texas         142000.0
Utah           10000.0
dtype: float64

### DataFrame

There are many ways to construct a DataFrame, though one of the most common is from a dictionary of equal-length lists or NumPy arrays.

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [ ]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
# head method selects only the first five rows
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [ ]:
# tail method selects only the last five rows
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

If you sepcify a sequence of columns, the DataFrame's columns will be arranged in that order.

In [ ]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

If you pass a column that isn't contained in the dictionary, it will appear with missing values in the result:

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

A column in a DataFrame can be retrieved as a Series either by dictionary-like notation or by using the dot attribute notation.

In [ ]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [ ]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

Rows can be retrieved by position or name with the special iloc and loc attributes.

In [ ]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [ ]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

Columns can be modified by assignment. A column can be assigned a scalar value or an array of values.

In [ ]:
frame2['debt'] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [ ]:
frame2.debt = np.arange(0.0, 6)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value's length must match the length of the DataFrame. If you assign a Series, its labels will be realigned exactly to the DataFrame's index, inserting missing values in any index values not present.

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7, 1.23], index=['two', 'four', 'five', 0])

In [ ]:
frame2['debt'] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  1.23
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Assigning a column that doesn't exist will create a new column. New column cannot be created with the frame2.eastern dot attribute notation.

In [ ]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  1.23     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

The `del` method can be used to remove a column.

In [ ]:
del frame2['eastern']

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
df1 =  frame2[['year', 'debt']]
print(df1._is_view)

df2 = frame2[['year', 'state']]
print(df2._is_view)

False
False

### Index Objects

pandas's Index objects are repsonsible for holding the axis labels (including a DataFrame's column names) and other metadata.

In [ ]:
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])

In [ ]:
index = obj.index

In [ ]:
index

Index(['a', 'b', 'c'], dtype='object')

Index objects are immutable and thus can't be modified by the user.

In [ ]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=index)

In [ ]:
obj2.index is index

True

In addition to being array-like, an Index also behaves like a fixed-size set.

In [ ]:
frame3 = pd.DataFrame({'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
                       'Nevada': {2001: 2.4, 2002: 2.9},
                       })

In [ ]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object')

In [ ]:
'Ohio' in frame3.columns

True

## 5.2 Essential Functionality

### Reindexing

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [ ]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Calling reindex on the Series rearranges the data according to the new index, introducing missing values if any index values were not already present.

In [ ]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [ ]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [ ]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(np.arange(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With DataFrame, reindex can alter the row index, columns or both.

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [ ]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

The columns can be reindexed with the columns keyword. Because 'Ohio' was not in states, the data for that column is dropped from the result.

In [ ]:
states = ['Texas', 'Utah', 'California']
frame3 = frame.reindex(columns=states)
frame3

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

We can also reindex by using the loc operator, and many users prefer to do it this way. This works only if all of the new index labels already exist in the DataFrame (whereas reindex will insert missing data for new labels)

In [ ]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame4 = frame.loc[['a', 'd', 'c'], ['Texas', 'Ohio']]
frame4

   Texas  Ohio
a      1     0
d      7     6
c      4     3

In [ ]:
frame4._is_view

True

### Dropping Entries from an Axis