<a href="https://colab.research.google.com/github/Mountain-Biker/pydata-book-practice/blob/main/chapter5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5. Getting Started with pandas

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## 5.1 Introduction to pandas Data Structures

### Series

A Series is a one-dimensional array-like object containing a sequence of values of the same type and an associated array of data labels, called its index.

In [2]:
obj = pd.Series([4, 5, -7, 3])

In [3]:
obj

0    4
1    5
2   -7
3    3
dtype: int64

In [4]:
obj2 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

In [5]:
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [6]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
obj2['a']

np.int64(1)

In [8]:
obj2['b'] = 6

In [9]:
obj2[['a', 'b']] = -1

In [10]:
obj2

a   -1
b   -1
c    3
d    4
dtype: int64

Using Numpy functions or Numpy-like operations, such as filtering with a Boolean array, scalar multiplication, or applying math functions, will preserve the index-value relationship.

In [11]:
obj2[obj2 > 0]

c    3
d    4
dtype: int64

In [12]:
obj2 * 2

a   -2
b   -2
c    6
d    8
dtype: int64

In [13]:
np.exp(obj2)

a     0.367879
b     0.367879
c    20.085537
d    54.598150
dtype: float64

Another way to think about a Series is as a **fixed-length, ordered dictionary**, as it is a mapping of index values to data values. It can be used in many context where you might use a dictionary.

In [14]:
'b' in obj2

True

In [15]:
'e' in obj2

False

A series can be created from a dictionary.

In [16]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

A series can be converted back to a dictionary with its to_dict method.

In [17]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
states = ['California', 'Utah', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [19]:
obj4

California        NaN
Utah           5000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

The isna and notna functions in pandas should be used to detect missing data.

In [20]:
pd.isna(obj4)

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

In [21]:
obj4.isna()

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [22]:
obj3 + obj4

California         NaN
Ohio               NaN
Oregon         32000.0
Texas         142000.0
Utah           10000.0
dtype: float64

### DataFrame

There are many ways to construct a DataFrame, though one of the most common is from a dictionary of equal-length lists or NumPy arrays.

In [23]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [24]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
# head method selects only the first five rows
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [26]:
# tail method selects only the last five rows
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

If you sepcify a sequence of columns, the DataFrame's columns will be arranged in that order.

In [27]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

If you pass a column that isn't contained in the dictionary, it will appear with missing values in the result:

In [28]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

A column in a DataFrame can be retrieved as a Series either by dictionary-like notation or by using the dot attribute notation.

In [29]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [30]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

Rows can be retrieved by position or name with the special iloc and loc attributes.

In [31]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [32]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

Columns can be modified by assignment. A column can be assigned a scalar value or an array of values.

In [33]:
frame2['debt'] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [34]:
frame2.debt = np.arange(0.0, 6)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value's length must match the length of the DataFrame. If you assign a Series, its labels will be realigned exactly to the DataFrame's index, inserting missing values in any index values not present.

In [35]:
val = pd.Series([-1.2, -1.5, -1.7, 1.23], index=['two', 'four', 'five', 0])

In [36]:
frame2['debt'] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  1.23
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Assigning a column that doesn't exist will create a new column. New column cannot be created with the frame2.eastern dot attribute notation.

In [37]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  1.23     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

The `del` method can be used to remove a column.

In [38]:
del frame2['eastern']

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [40]:
df1 =  frame2[['year', 'debt']]
print(df1._is_view)

df2 = frame2[['year', 'state']]
print(df2._is_view)

False
False

### Index Objects

pandas's Index objects are repsonsible for holding the axis labels (including a DataFrame's column names) and other metadata.

In [41]:
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])

In [42]:
index = obj.index

In [43]:
index

Index(['a', 'b', 'c'], dtype='object')

Index objects are immutable and thus can't be modified by the user.

In [44]:
# index[1] = 'd'

In [45]:
obj2 = pd.Series([1.5, -2.5, 0], index=index)

In [46]:
obj2.index is index

True

In addition to being array-like, an Index also behaves like a fixed-size set.

In [47]:
frame3 = pd.DataFrame({'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
                       'Nevada': {2001: 2.4, 2002: 2.9},
                       })

In [48]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [49]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object')

In [50]:
'Ohio' in frame3.columns

True

## 5.2 Essential Functionality

### Reindexing

In [51]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [52]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Calling reindex on the Series rearranges the data according to the new index, introducing missing values if any index values were not already present.

In [53]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [54]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [55]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [56]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [57]:
obj3.reindex(np.arange(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With DataFrame, reindex can alter the row index, columns or both.

In [58]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [59]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [60]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

The columns can be reindexed with the columns keyword. Because 'Ohio' was not in states, the data for that column is dropped from the result.

In [61]:
states = ['Texas', 'Utah', 'California']
frame3 = frame.reindex(columns=states)
frame3

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

We can also reindex by using the loc operator, and many users prefer to do it this way. This works only if all of the new index labels already exist in the DataFrame (whereas reindex will insert missing data for new labels)

In [62]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [63]:
frame4 = frame.loc[['a', 'd', 'c'], ['Texas', 'Ohio']]
frame4

   Texas  Ohio
a      1     0
d      7     6
c      4     3

In [64]:
frame4._is_view

True

### Dropping Entries from an Axis

In [65]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])

In [66]:
new_obj = obj.drop('c')

In [67]:
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [68]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [69]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Calling drop with a sequence of labels will drop values from the row labels.

In [70]:
data.drop(['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [71]:
data.drop(index=['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

To drop labels from the columns, use the columns keyword.

In [72]:
data.drop(columns=['two'])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [73]:
data.drop(['two', 'four'], axis=1)

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, Selection and Filtering

In [74]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [75]:
obj['a']

np.float64(0.0)

In [76]:
# Not a good way to use integer position to access a value in Series
# Should use obj.iloc[] instead
obj[1]

<ipython-input-76-0ceebe4fe905>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [77]:
obj[[1, 2]]

<ipython-input-77-76ca706e5645>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 2]]

b    1.0
c    2.0
dtype: float64

In [78]:
obj[['b', 'c', 'a']]

b    1.0
c    2.0
a    0.0
dtype: float64

In [79]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [80]:
obj.loc[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

When using `loc`, the expression `obj.loc[[0, 1, 2]]` will fail when the index does not contain integers.

In [81]:
# obj.loc[[0]]

Since `loc` operator indexes exclusively with labels, there is also an iloc operator that indexes exclusively with integers to work consistently whether or not the index contains integers.

In [82]:
obj.iloc[[1, 2]]

b    1.0
c    2.0
dtype: float64

In [83]:
obj.loc['c': 'd']

c    2.0
d    3.0
dtype: float64

In [84]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'Nevada'],
                    columns=['one', 'two', 'three', 'four'])

In [85]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
Nevada     12   13     14    15

Indexing into a DataFrame retrieves one or more columns either with a single value or sequence:

In [86]:
data['two']

Ohio         1
Colorado     5
Utah         9
Nevada      13
Name: two, dtype: int64

In [87]:
data[['two', 'three']]

          two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
Nevada     13     14

If we want to retrieve rows with indexing, we should use integer positions:

In [88]:
data[0:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [89]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
Nevada    False  False  False  False

In [90]:
data[data < 5]

          one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
Nevada    NaN  NaN    NaN   NaN

### Selection on DataFrame with loc and iloc

In [91]:
data.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [92]:
data.loc[['Colorado', 'Utah']]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [93]:
data.loc[['Utah', 'Nevada'], 'one']

Utah       8
Nevada    12
Name: one, dtype: int64

In [94]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [95]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [96]:
data.iloc[[2, 1], [1, 3]]

          two  four
Utah        9    11
Colorado    5     7

In [97]:
data.iloc[:, 1]

Ohio         1
Colorado     5
Utah         9
Nevada      13
Name: two, dtype: int64

### Pitfalls with Chained indexing

When trying to modify values in a dataframe in place, we should always use loc and iloc.

In [98]:
data.loc[data.three > 5]['three'] = 6

<ipython-input-98-e95134e02e88>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three > 5]['three'] = 6

The above code will return a SettingWithCopyWarning, because `data.loc[data.three > 5]` will return a copy of the original DataFrame. So the code will modify the copy of the dataframe but not the origial one. To fix the issue, we should use a single loc operation:

In [99]:
data.loc[data.three > 5, 'three'] = 6

In [100]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9      6    11
Nevada     12   13      6    15

### Arithmetic and Data Alignment

When you add objects, if any index pairs are not the same, the respective index in the result will be the union of the index pairs. The internal data alignment introduces missing values in the label locations that don't overlap.

In [102]:
s1 = pd.Series([7, -2, 3, 1], index=['a', 'b', 'c', 'e'])

In [101]:
s2 = pd.Series([2, 3, 4], index=['a', 'c', 'd'])

In [103]:
s1 + s2

a    9.0
b    NaN
c    6.0
d    NaN
e    NaN
dtype: float64

In [113]:
df1 = pd.DataFrame(np.arange(0, 9.0).reshape((3, 3)),
                   columns=list('bcd'),
                   index=['Utah', 'Colorado', 'Nevada'])
df1

            b    c    d
Utah      0.0  1.0  2.0
Colorado  3.0  4.0  5.0
Nevada    6.0  7.0  8.0

In [114]:
df2 = pd.DataFrame(np.arange(0, 12.0).reshape((4, 3)),
                   columns=list('bde'),
                   index=['Ohio', 'Utah', 'Nevada', 'Colorado'])
df2

            b     d     e
Ohio      0.0   1.0   2.0
Utah      3.0   4.0   5.0
Nevada    6.0   7.0   8.0
Colorado  9.0  10.0  11.0

In [115]:
df1 + df2

             b   c     d   e
Colorado  12.0 NaN  15.0 NaN
Nevada    12.0 NaN  15.0 NaN
Ohio       NaN NaN   NaN NaN
Utah       3.0 NaN   6.0 NaN

#### Arithmetic methods with fill values

In [116]:
df1.add(df2, fill_value=0)

             b    c     d     e
Colorado  12.0  4.0  15.0  11.0
Nevada    12.0  7.0  15.0   8.0
Ohio       0.0  NaN   1.0   2.0
Utah       3.0  1.0   6.0   5.0