<a href="https://colab.research.google.com/github/Mountain-Biker/pydata-book-practice/blob/main/chapter5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5. Getting Started with pandas

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## 5.1 Introduction to pandas Data Structures

### Series

A Series is a one-dimensional array-like object containing a sequence of values of the same type and an associated array of data labels, called its index.

In [3]:
obj = pd.Series([4, 5, -7, 3])

In [4]:
obj

0    4
1    5
2   -7
3    3
dtype: int64

In [5]:
obj2 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

In [6]:
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
obj2['a']

1

In [9]:
obj2['b'] = 6

In [10]:
obj2[['a', 'b']] = -1

In [11]:
obj2

a   -1
b   -1
c    3
d    4
dtype: int64

Using Numpy functions or Numpy-like operations, such as filtering with a Boolean array, scalar multiplication, or applying math functions, will preserve the index-value relationship.

In [12]:
obj2[obj2 > 0]

c    3
d    4
dtype: int64

In [13]:
obj2 * 2

a   -2
b   -2
c    6
d    8
dtype: int64

In [14]:
np.exp(obj2)

a     0.367879
b     0.367879
c    20.085537
d    54.598150
dtype: float64

Another way to think about a Series is as a **fixed-length, ordered dictionary**, as it is a mapping of index values to data values. It can be used in many context where you might use a dictionary.

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

A series can be created from a dictionary.

In [17]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

A series can be converted back to a dictionary with its to_dict method.

In [18]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
states = ['California', 'Utah', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [20]:
obj4

California        NaN
Utah           5000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

The isna and notna functions in pandas should be used to detect missing data.

In [21]:
pd.isna(obj4)

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

In [22]:
obj4.isna()

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [23]:
obj3 + obj4

California         NaN
Ohio               NaN
Oregon         32000.0
Texas         142000.0
Utah           10000.0
dtype: float64

### DataFrame

There are many ways to construct a DataFrame, though one of the most common is from a dictionary of equal-length lists or NumPy arrays.

In [24]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [25]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
# head method selects only the first five rows
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [27]:
# tail method selects only the last five rows
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

If you sepcify a sequence of columns, the DataFrame's columns will be arranged in that order.

In [28]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

If you pass a column that isn't contained in the dictionary, it will appear with missing values in the result:

In [30]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

A column in a DataFrame can be retrieved as a Series either by dictionary-like notation or by using the dot attribute notation.

In [31]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [32]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

Rows can be retrieved by position or name with the special iloc and loc attributes.

In [37]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [38]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

Columns can be modified by assignment. A column can be assigned a scalar value or an array of values.

In [39]:
frame2['debt'] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [45]:
frame2.debt = np.arange(0.0, 6)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [ ]:
val = pd.Series